### ISSUE TITLE
Why isn't this done yet???????????

### ISSUE THREAD

**Issue by starrodkirby86** [adamhabib25/MessageInABottle#3]
I am feeling incredibly lonely, and I need someone to desperately read my messages in bottles, jugs, and other cylindrical, phallic shaped objects. When can I expect an ETA? Once this project is done, I will pirate it off you guys out of principle. Then I will make a port of this app using Java, then call it JarrMatey.

tl;dr: u w0t m8

Sincerely,
Unreasonable client

**Comment by BlueCrimson** [comment]
I agree, the cheeto stains on my shirt is bringing me much anguish, and I MUST let someone (preferably anonymous and on the receiving end of a virtual bottle) know using this program. Please, please, for the love of everything that is blessed by the cheeto gods, finish this program.

Sincerely,
Concern cheeto enthusiast

**Comment by starrodkirby86** [comment]
mfw i give your team pressure to finish this semester
![](http://i.imgur.com/o0Ds3oE.gif)

**Comment by starrodkirby86** [comment]
Thanks Jason! I'm glad that you realized that this is a legitimate problem that needs to be solved! :^)

**Comment by BrennenFagan** [comment]
Almost there ; )

**Comment by jhernandez5922** [comment]
Just Published!
