### ISSUE TITLE
Inventory Default Message Viewable behind Bottles

### ISSUE THREAD

**Issue by BrennenFagan** [adamhabib25/MessageInABottle#8]
Simple if statement style fix?

**Comment by jhernandez5922** [comment]
I can't get this one to properly work, because if you put it in onResume, the data has not loaded yet so the item count will always return 0. Looking in to a different way of providing the empty screen. As for now, it is just blank.

**Comment by jhernandez5922** [comment]
Removed it, we will try this again later. Will reopen when attempting once again.
